version: 2.1

jobs:
  build:
    working_directory: ~/repo
    docker:
       - image: cimg/node:18.18

    steps:
     - checkout

     - setup_remote_docker:
          version: 20.10.24
          docker_layer_caching: true

     - run:
          name: Create docker image
          command: docker build -t circleci-node:latest .

workflows:
  version: 2
  main:
    jobs:
      - build
